### ISSUE TITLE
SD card format for LCD Touchscreen and contents directory

### ISSUE THREAD

**Issue by daveclifford** [DCC-EX/EX-T3-WiFi#10]
I am following your project and replicating the DCC WiFi Throttle. I will send you an email on my correspondence re: the 3D case. You may find it interesting.

1. I need to know what type of format the MicroSD card for the Touchscreen display should be in - FAT12, FAT16, FAT32 or some other format. I decided to use FAT32 for an 8GB MicroSD card
2. . The list below depicts the format of files on the SD card, so the user can see a  /icon folder containg the icon .bmp files and a default.json base file.  You may wish to add this to your explanation " This needs to be the contents of the `sd` folder and not the folder itself, the files need to be copied to the root of the SD card." 
3. I truely appreciate the work you have done to help the hobby and me.4. 

/icons/brake-off.bmp
/icons/brake-on.bmp
/icons/bulb-off.bmp
/icons/bulb-on.bmp
/icons/compressor-off.bmp
/icons/compressor-on.bmp
/icons/engine-off.bmp
/icons/engine-on.bmp
/icons/fan-off.bmp
/icons/fan-on.bmp
/icons/flange-squeal-off.bmp
/icons/flange-squeal-on.bmp
/icons/horn-off.bmp
/icons/horn-on.bmp
/icons/two-horn-off.bmp
/icons/two-horn-on.bmp
/icons/whistle-off.bmp
/icons/whistle-on.bmp
default.json

**Comment by alex-code** [comment]
The SD needs to be FAT32.
I'm not the best at documentation so any input on bits that could use improvement are a big help 👍

**Comment by daveclifford** [comment]
I suggest you consider the following changes in the assembly.md file
Replace "This needs to be the contents of the sd folder and not the folder itself, the files need to be copied to the root of the SD card."  with the following 3 sentences:
- The files in the /sd directory should not exceed 4 GB  or 8 GB in size; however a 16GB MicroSD card should work well.
- The Micro SD card needs to be formatted FAT32 before the files contained in the /sd directory are copied to the Micro SD card.
- After copying the /sd directory to the Micro SD card, the Micro SD card directory structure will contain the file 'default.json' and a directory named 'icons'  (which contains the icons for the Touchscreen use).

**Comment by daveclifford** [comment]
"I'm not the best at documentation so any input on bits that could use improvement are a big help"

I  worked for IBM for 40 years, have written documentation for many successful  projects and will give you suggestions to improve the documentation. So far, you've done a very good job in organizing/documenting  the project. 
I use Linux as my development platform O/S and  may offer you a short summary  so others may have an easier time to build the ESP32-E microcontroller load.

**Comment by daveclifford** [comment]
Nice work! Those words are clearer for the builder.  I am getting 2 cases
3-D printed - 1 commercially and the other through my nephew. The
commercial one   is being made by modelsceneryworld.com. I went to a Model
train show after our Thanksgiving and the 20% discounted cost will be "FDM
Dynamic Quality - $78 (disc 20% $62)".

(My oldest sister has lived  in England (now in Nottingham) since 1962) .
I also liked the beginning of your Youtube video - celebrating the work.
The case is fantastic - took a lot of thought and planning.
I think that the FireBeetle board is great!
What do you do for a living? I am retired from IBM and the US Air Force
Reserve

**Comment by alex-code** [comment]
If you plan on doing a lot of custom parts it's worth getting a 3D printer, I'd say they're pretty affordable these days.

Haha, the intro was just a silly idea I had ;)

The case did have a few iterations until I was happy.
For me I thought the FireBeetle was a good choice as it had the functionality I wanted plus the ribbon cable to the display making the wiring simpler.

My day job is web dev so I'm used to languages with memory garbage collection so I may miss things.
Trains and embedded programming are hobbies.

**Comment by daveclifford** [comment]
(This  is the guy I am having the 3-D case printed)
Marc Scott
4:44 PM (4 hours ago)
to me
Hi Dave,

Invoice is on the way, Print will finish tonight (12-10) and ship Monday
morning via USPS. You should have it mid week given it only has to travel a
few miles :)

I would love to see the completed remote when you get it done. It's a neat
little project.

*I did find a few minor errors in the files and fixed them with no charge,
nothing major, mostly surfaces that were not manifold. The overall design
was very well done and even with the errors I am sure it would have printed
well. Making sure all of the surfaces are manifold in FDM just gives a
little cleaner print and stronger infill profile. *

When you get the case, let me know what you think of the color, texture,
fit, and feel.

**Comment by daveclifford** [comment]
The additions to the documentation for the SD card are welcome to help others as well as me.
