### ISSUE TITLE
Wi-Fi does not connect if password contains "$"

### ISSUE THREAD

**Issue by FDrebin** [DCC-EX/EX-T3-WiFi#101]
**Describe the bug**
When entering wireless password for the local Wi-Fi network (not Wi-Fi broadcasted from DCC EX system) and it contains a "$" the wireless network does not connect.

**To Reproduce**
1. Create wireless network with password containing "$"
2. Navigate to throttle setup
3. Enter Wi-Fi name and its associated password that contains "$"
4. Save settings
5. Watch Wi-Fi not connect

**Expected behavior**
Wireless connects to network.

**Screenshots or debug output**
If applicable, add screenshots or debug output to help explain your problem.
*Debug output can be obtained from the serial monitor*

**Additional info**
![NotWorking](https://github.com/DCC-EX/EX-T3-WiFi/assets/13129353/da39c36a-a499-4a75-a644-3615b2ef2126)
![Working](https://github.com/DCC-EX/EX-T3-WiFi/assets/13129353/eb9db321-f4fe-46b8-b2b5-6fd98778aa90)

 - Component: All purchased from links provided
 - FireBettle version 1.0

**Comment by alex-code** [comment]
That's an odd one, will try and get a test setup to see if I can reproduce.

**Comment by alex-code** [comment]
Tested on my home WiFi by adding a $ in different places in the password but it connected.

Have you got a mac filter or any other type of security which could block the throttle?

There's a small example on the DFRobot wiki you could try to see if that has the same problem. It'll print to the serial monitor.

https://wiki.dfrobot.com/FireBeetle_Board_ESP32_E_SKU_DFR0654 - 10.3.2 Getting Network Time via WiFi
