### ISSUE TITLE
Throttle setup page becomes unreachable when on local wireless network

### ISSUE THREAD

**Issue by FDrebin** [DCC-EX/EX-T3-WiFi#102]
**Describe the bug**
When throttle is connected to wireless network (not in AP mode for setup), throttle receives IP address, setup web page is reachable for 30-60 seconds, then becomes unreachable. Device still pings, but performing telnet to port 80 results in unreachable.

**To Reproduce**
1. Join throttle to wireless network
2. Perform network scan to determine IP address
3. Open web browser to throttles IP address
4. Wait for several minutes/try navigating webpage
5. Wait for webpage to time out

**Expected behavior**
Throttle setup remains reachable for as long as throttle is powered on and connected to wireless network.

**Screenshots or debug output**
If applicable, add screenshots or debug output to help explain your problem.
*Debug output can be obtained from the serial monitor*

**Additional info**
 - Component: All items purchased from links on Github page
 - Firebettle 2 version 1.0

**Comment by alex-code** [comment]
I can reproduce something similar.
My AP seems to lose the throttle hostname after about a minute but I can still use the throttles IP to access the settings website.

When trying to connect were you on the T3 WiFi display?
The built in web server is only active while on this display.
