### ISSUE TITLE
Project change for ESP32S3 - WROOM1-N16R8

### ISSUE THREAD

**Issue by JozefKc** [DCC-EX/EX-T3-WiFi#109]
I would like to ask you, if possible.
I have a **LILYGO T7-S3** what is an _ESP32-S3-WROOM-1-N16R8_ =16M Flash a and 8MB PRAM. I would like to use this processor and I do not have enough experience to change this project. I think it will be useful for many users too.
Best regards.
Joe

**Comment by alex-code** [comment]
Extra boards isn't something I can support due to the multi component nature of the project and the 3D parts will only fit the components I've used.

To make development and construction simpler it's easier to use a standard set of components.
