### ISSUE TITLE
No loco functions except forward, reverse and speed.

### ISSUE THREAD

**Issue by Budman1758** [DCC-EX/EX-T3-WiFi#63]
**Describe the bug**
When in the loco screen all I have is fwd & rev and speed. Seems like there should be more "stuff" Is this normal? The fwd ,rev  and speed functions work as they should as far as I can tell. Followed the code upload directions to the letter. (pretty sure anyway)
See attached picture.

![PXL_20230220_013728782](https://user-images.githubusercontent.com/6570134/219996259-3ad41f74-69ff-4c31-b1dc-8e2dd71cbea0.jpg)

**Screenshots or debug output**
If applicable, add screenshots or debug output to help explain your problem.

**Comment by alex-code** [comment]
Can you tell me what version your CS is?
You'll need to be on the latest ideally as it has new functionality the throttle requires.

**Comment by Budman1758** [comment]
I used the Windows installer so I assume it is the latest release version.

**Comment by alex-code** [comment]
Do you have a MicroSD card in the throttle with the contents of the sd folder copied?
https://github.com/DCC-EX/EX-T3-WiFi/blob/master/docs/assembly.md#before-starting-assembly

**Comment by Budman1758** [comment]
OK. That helps. Don't have any idea how I missed that part.... Musta had a senior moment there...lol. Now I have all the buttons on the loco screen. 

Are the icons only assigned to function buttons when customized individually? No "default" icon setup?

**Comment by alex-code** [comment]
I didn't include icons with the default function buttons as they may vary between different decoders.

You can create a reusable function set if you've got the same decoders so you don't have to create one with each loco.

**Comment by Budman1758** [comment]
Got a good source for appropriate icons? Lots of .svg and .png stuff but not .bmp.

**Comment by alex-code** [comment]
I got some icons from here https://www.pngrepo.com then just resized (30x30) and converted to 24bit bmp.
This is a good free image editor program https://www.getpaint.net
