### ISSUE TITLE
Disable swipe option

### ISSUE THREAD

**Issue by giraffe167** [DCC-EX/EX-T3-WiFi#67]
Sometimes I have noticed that I accidently swipe on the screen and it can get a little annoying. 

Could you possibly make a button in the settings so you could disable swipe?

**Comment by alex-code** [comment]
Good idea, I could add an extra `No Action` option to the swipe config.

**Comment by alex-code** [comment]
Added `None` as an option for swipe actions.
This is a breaking change as I reordered the const numbers so you'll just need to touch each action option button once if you want to keep any settings you previously had.

**Comment by giraffe167** [comment]
Hi i have uploaded the new code but the none button isn't showing as an option, but i have got:

Release/Keypad/Loco Names/Loco groups/Next Loco/ Prev Loco

**Comment by alex-code** [comment]
Does it show when you cycle through the swipe options by touching the buttons?

**Comment by giraffe167** [comment]
When pressing the swipe options, the none button doesn't show on the list

**Comment by alex-code** [comment]
How did you update?
Did you download the new changes then upload?

**Comment by giraffe167** [comment]
Sorted it i accidentally pressed the wrong upload button

Thank you for your help
