### ISSUE TITLE
Multiple EX-TC-WiFi throttles....  Same hostname.

### ISSUE THREAD

**Issue by Budman1758** [DCC-EX/EX-T3-WiFi#88]
**Is your feature request related to a problem? Please describe.**
When you have more than one of these they all have the same hostname. This can be a problem when trying to access the web config.

**Describe the feature you'd like**
The ability to define a custom hostname per throttle.

**Additional context**
I'm sure this is possible but unsure where to define this before uploading the code.

**Comment by alex-code** [comment]
This has been changed so the throttle generates it's own random one now so would be unique per throttle.

I tried to make it backwards compatible so the throttle name wouldn't change when updating but this would've used the same name for each upload.

To manually set or generate a new one you'll need to remove this file `include/ThrottleWiFiSettings.h` in the code then edit the `settings.json` file on the MicroSD card.

You can edit the `settings.json` file with any text editor, like notepad.
If you find the bit `DCCEX-T3-xxxx` where the xxxx is the random bit you can set your own.
