### ISSUE TITLE
3d print possible issue

### ISSUE THREAD

**Issue by Wreckingball7** [DCC-EX/EX-T3-WiFi#94]
JLCPCB reports that when printing the top there is a very narrow section which might not print correctly.
This is at the top narrow end inside of the cover. Not sure how to correct this myself.
![JLCPCB](https://github.com/DCC-EX/EX-T3-WiFi/assets/67566877/41b405ca-5609-467b-9640-6b5cedb44b44)

**Comment by alex-code** [comment]
There's not really anything I can change.
The large red area shown above covers a ribbon cable for the display, if it was made thicker the top might not fit or could rub on the ribbon cable.
This section could be removed but would just look less finished.

The case was designed with FDM printers in mind.
